<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import Button from 'primevue/button'; import Message from 'primevue/message'; import Skeleton from 'primevue/skeleton'
import { weatherEmoji } from '../data/cities'; import { useTemperature } from '../composables/useTemperature'; import { useConfigStore } from '../stores/configStore'; import { useWeatherStore } from '../stores/weatherStore'; import { readableApiError } from '../services/http'
const props = defineProps({ cityId: { type: String, required: true } }); const router = useRouter(); const store = useWeatherStore()
const city = computed(() => store.getCity(props.cityId)); const configStore = useConfigStore(); const forecast = ref([]); const loading = ref(false); const error = ref('')
const cityTemp = computed(() => city.value?.temp ?? 0); const { displayTemp, unitSymbol } = useTemperature(cityTemp)
const convertTemp = (value) => configStore.unit === 'fahrenheit' ? Math.round((Number(value) * 9) / 5 + 32) : Math.round(Number(value))
async function load(){ if(!city.value)return; loading.value=true; error.value=''; try{forecast.value=await store.loadForecast(city.value)}catch(e){error.value=readableApiError(e)}finally{loading.value=false} }
onMounted(()=>{if(city.value){store.selectCity(city.value.id);load()}})
</script>
<template><main class="detail-page"><section v-if="city" class="detail-wrap">
  <Button label="대시보드로" icon="pi pi-arrow-left" text @click="router.push('/')" />
  <header class="detail-hero"><div><p>WEATHER OBSERVATION</p><h1>{{ city.name }}</h1><span>{{ city.status }}</span></div><div class="hero-temp"><span>{{ weatherEmoji(city.icon) }}</span>{{ displayTemp }}<small>{{ unitSymbol }}</small></div></header>
  <dl class="detail-stats"><div><dt>체감 온도</dt><dd>{{ convertTemp(city.feelsLike) }}{{ unitSymbol }}</dd></div><div><dt>습도</dt><dd>{{ city.humidity }}%</dd></div><div><dt>풍속</dt><dd>{{ city.wind }}m/s</dd></div><div><dt>강수</dt><dd>{{ city.rain }}%</dd></div></dl>
  <section class="forecast"><p class="eyebrow">5 DAY / 3 HOUR FORECAST</p><h2>앞으로의 날씨</h2><Message v-if="error" severity="warn">{{ error }}</Message><div v-if="loading" class="forecast-grid"><Skeleton v-for="i in 5" :key="i" height="170px" /></div><div v-else-if="forecast.length" class="forecast-grid"><article v-for="item in forecast" :key="item.id"><time>{{ new Date(item.date).toLocaleDateString('ko-KR',{weekday:'short',month:'short',day:'numeric'}) }}</time><span>{{ weatherEmoji(item.icon) }}</span><strong>{{ convertTemp(item.temp) }}{{ unitSymbol }}</strong><p>{{ item.status }}</p><small>강수 {{ item.rain }}%</small></article></div><div v-else class="forecast-empty">예보 데이터가 없습니다. API 키와 네트워크를 확인해주세요.</div></section>
  </section><section v-else class="missing"><h1>도시를 찾을 수 없습니다.</h1><p>잘못된 도시 코드이거나 아직 불러오지 않은 도시입니다.</p><Button label="홈으로 돌아가기" @click="router.push('/')" /></section></main></template>
<style scoped>.detail-page{min-height:calc(100vh - 70px);padding:42px 24px 80px}.detail-wrap{width:min(980px,100%);margin:auto}.detail-hero{display:flex;align-items:center;justify-content:space-between;gap:30px;padding:40px;margin-top:14px;color:#fff;background:linear-gradient(135deg,var(--primary-900),var(--primary-700));border-radius:16px}.detail-hero p,.eyebrow{margin:0 0 8px;font-size:10px;font-weight:700;letter-spacing:1.4px;opacity:.72}.detail-hero h1{margin:0;font-size:50px;font-weight:700;letter-spacing:-1.6px}.detail-hero span{opacity:.8}.hero-temp{display:flex;align-items:center;font-size:62px;font-weight:800}.hero-temp>span{margin-right:18px;font-size:58px}.hero-temp small{font-size:19px}.detail-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0 48px}.detail-stats div{padding:18px;background:#fff;border:1px solid var(--grey-200);border-radius:10px}.detail-stats dt{color:#8491a0;font-size:12px}.detail-stats dd{margin:7px 0 0;font-size:21px;font-weight:800}.forecast h2{margin:0 0 18px;color:var(--primary-900);font-size:26px;font-weight:700;letter-spacing:-.8px}.forecast-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.forecast article{padding:20px;text-align:center;background:#fff;border:1px solid var(--grey-200);border-radius:10px}.forecast article span{display:block;margin:13px 0;font-size:34px}.forecast article strong{font-size:20px}.forecast article p{min-height:30px;color:#63758a;font-size:12px}.forecast article small{color:var(--primary-700)}.forecast-empty,.missing{padding:50px;text-align:center;background:#fff;border-radius:12px}.missing{width:min(650px,100%);margin:60px auto}@media(max-width:700px){.detail-hero{align-items:flex-start;flex-direction:column}.forecast-grid{grid-template-columns:repeat(2,1fr)}.detail-stats{grid-template-columns:repeat(2,1fr)}} </style>
